### ISSUE TITLE
integer overflow in decode_ltc

### ISSUE THREAD

**Issue by jossgray** [x42/libltc#25]
In `decoder.c`, `decode_ltc` method, lines 309, 310, 317; the `int offset` parameter of `biphase_decode2` can overflow if `i > INT32_MAX`.

Changing `offset` to an `int` would require changing the public API, so that's probably a no go. Is it ok to early out if `i > INT32_MAX`?

**Comment by x42** [comment]
indeed, but are you really feeding INT32_MAX samples into the decoder in one go?

Since neither `decode_ltc` nor `biphase_decode2` are part of the public API,   `offset` can be changed to `size_t offset`,  or to be safe with additions to `posinfo` to `ltc_off_t`.  Can you elaborate how this would change the public API?

**Comment by jossgray** [comment]
No probably not.

My suggestion off changing `offset` to an `int` would change the public api. Yours is better.

**Comment by x42** [comment]
This is really rather an edge-case. Compilers should promote the int when adding it to 
`ltc_off_t` aka long long.

Anyway the limit would be UINT32_MAX since  `size_t i` is unsigned per spec and I don't see how it could overflow since `sizeof(posinfo) > sizeof (size)` aka sizeof(long long) > sizeof (long) as per C spec. And one can at most feed `sizeof(size)` samples into the decoder

Still the internal API is a bit cleaner with the following change:

```diff
diff --git a/src/decoder.c b/src/decoder.c
index da60eeb..417aeb2 100644
--- a/src/decoder.c
+++ b/src/decoder.c
@@ -118,7 +118,7 @@ static double calc_volume_db(LTCDecoder *d) {
        return (20.0 * log10((d->snd_to_biphase_max - d->snd_to_biphase_min) / 255.0));
 }
 
-static void parse_ltc(LTCDecoder *d, unsigned char bit, int offset, ltc_off_t posinfo) {
+static void parse_ltc(LTCDecoder *d, unsigned char bit, ltc_off_t offset, ltc_off_t posinfo) {
        int bit_num, bit_set, byte_num;
 
        if (d->bit_cnt == 0) {
@@ -259,7 +259,7 @@ static void parse_ltc(LTCDecoder *d, unsigned char bit, int offset, ltc_off_t po
        }
 }
 
-static inline void biphase_decode2(LTCDecoder *d, int offset, ltc_off_t pos) {
+static inline void biphase_decode2(LTCDecoder *d, ltc_off_t offset, ltc_off_t pos) {
 
        d->biphase_tics[d->biphase_tic] = d->snd_to_biphase_period;
        d->biphase_tic = (d->biphase_tic + 1) % LTC_FRAME_BIT_COUNT;

```

what do you think?
