### ISSUE TITLE
29.97fps drop/non-drop frame 

### ISSUE THREAD

**Issue by simnedonadni** [x42/libltc#37]
Hi,
i got a problem decoding audio files at 29.97fps dropping and non-drop frame.
It is like at 29.97fps ndf i am losing a 1second every 30mins, and at 29.97 i am gaining a 1 second every 30mins.
I have been looking at ltc_frame_to_time() but i do not see where i can find a solution.
Do you have any advice?
Cheers,
S.

**Comment by x42** [comment]
Could you try to rephrase the question?  What do you mean with **loose** 1 second?

Decoding just decodes previously encoded data.  LTC has no inherent concept of fps. it's just a datastream clocked at a given rate.

**Comment by simnedonadni** [comment]
I am trying to decode some audio files generated from http://elteesee.pehrhovey.net/ 
Everything works fine at 24/25/30fps. But with 29.97ndf the smtpe times i get from ltc_frame_to_time() are increasingly smaller than what they should be. After 90’ I read 89’55”. While using 29.97df they are increasingly bigger, after 90’ I will get 90’05”.
By the way inside ltc_time_to_frame() there is a skip_drop_frames() function. 
So I was wondering if the decoder can accept only integer frame rate.
Thank you. 
s.

**Comment by x42** [comment]
`ltc_time_to_frame()` is not used at all when decoding LTC.
Since LTC is vari-speed, decoding does not care about sample-rate at all. So this is odd. A decoder really just decodes.

One explanation would be an issue with the encoder. One LTC frame is  (sample-rate * 1001 / 30000) ~ 1601.60 audio-samples per video-frame @48kHz. The encoder will have to equally distribute frames and not round it to an integer. That could add up to ~5 seconds for 90mins.

Can you try some different LTC encoder, perhaps some hardware encoder?
Another test would be 44.1kHz / 24fps (that is 1837.50 audio-samples/frame).


PS. There is no LTC spec for 29.97non-drop.  LTC officially only support 24, 25, 29.97df and 30 fps.

**Comment by simnedonadni** [comment]
I have tried with 24fps 44.1kHz, and it was fine.
I will try with other encoders and I will let you know.
Thank you!

**Comment by simnedonadni** [comment]
Hi there,
actually it was a problem with the files,  i got the same errors reading them with some hardware decoder.
Thank you!
bye,
S.

**Comment by x42** [comment]
Do you know if it is a general issue with   http://elteesee.pehrhovey.net/  or just a specific file?

**Comment by simnedonadni** [comment]
I have tested with some 3h long files from http://elteesee.pehrhovey.net/ , but i was getting the drift just at 29.97df/ndf. I downloaded just one file for sample rate, so i do not know if it is specific of just that file.. The other tests were made using LTC generated from Reaper and a Rosendahl MIF3 and i with them i got the expected results.
