### ISSUE TITLE
Unable to read by decoder

### ISSUE THREAD

**Issue by cmalvin121** [x42/libltc#71]
I'm encountering a problem with ltc_decoder_read, I found out that the queue_read_off and queue_write_off are both 0 which cause ltc_decoder_read fail to read data. I'm confuse why queue_read_off and queue_write_off would be 0 in value. Am I using the wrong setting for decoder?

I've used ffmpeg to check the sample format and using the same setting for the decoder.

Here's the info. output from ffmpeg:
sample_fmt=s16
sample_rate=48000
channels=2
bit_rate=1536000

My code:
![螢幕擷取畫面 2024-09-04 112403](https://github.com/user-attachments/assets/5cc157a8-5308-4fb6-bc82-d3facd325a64)

**Comment by cmalvin121** [comment]
https://drive.google.com/file/d/1aJNUgzJ6CvRZ5D-SxJvDKbXb3NJcLEJx/view?usp=sharing

Here's the wav file using in the project.

**Comment by x42** [comment]
It looks like this is a stereo file with timecode only on the 1st channel, so you need to skip the 2nd channel when reading data. Either first de-interleave it into a buffer, or feed 1 sample at a time with offsets to the existing buffer.

[ltcdump](https://github.com/x42/ltc-tools/) finds some data, but mostly garbage, which isn't too surprising since the signal is rather corrupted. Looks like there is a low pass filter or perhaps some phase rotation applied to the signal:
![image](https://github.com/user-attachments/assets/45dfd644-1b16-4d94-b1de-c4456a025fa1)

LTC is encoded in a 2/4kHz ***square*** wave with 40 us rise time.

**Comment by x42** [comment]
How did you record this Timecode.wav? When I rotate the phase by 45 deg it does resemble LTC and decodes properly:

![image](https://github.com/user-attachments/assets/181700bd-77d1-4bdc-9320-e51df981b880)

However since LTC decoder is signal-level dependent, it cannot detect timecode in the file you provided as-is.

**Comment by x42** [comment]
You can find a test file to check your decoder https://robin.linuxaudio.org/tmp/ltc-25fps_1min.wav  (PCM S16LE, 48kHz, mono)

**Comment by cmalvin121** [comment]
The Timecode.wav is extracted from a video using ffmpeg. I found a website ( https://0110.be/attachment/cors/ltc.wasm/ltc_decoder.html ) which can detect the timecode of this file. Because this website is using your library too, thats why I believe there must be some problem in my code.

Many thanks for replying, I will try the test file you have provided.

**Comment by cmalvin121** [comment]
Hi, here's an update. My code works perfectly with the test file, it extracts the timecode correctly as expected!

I wonder if I am missing something when extracting the audio from a video, which cause the signal getting polluted.
Maybe I should try to identify the waveform of signal and rotate it into standard LTC format?

Please forgive any inaccuracies or lack of professionalism in my terminology, as my knowledge of sound waves is limited. Thank you for your understanding.

**Comment by cmalvin121** [comment]
I have utilized your phaserotate.lv2 plugin to rotate the Timecode.wav by 45 degrees, and as you indicated, the timecode was successfully detected afterward. However, I am still unclear on how to determine whether the phase of an audio signal requires rotation in order to correctly match the LTC waveform.

Really appreciate your help. Wishing you a wonderful day.

**Comment by x42** [comment]
Another idea add a steep low pass filter. That'll work more generically. I tested with a 4th order filter (48dB/octave) at 4.5kHz with a bit of resonance:

![image](https://github.com/user-attachments/assets/06870ea8-3067-4267-a8ab-375ea9ee6af0)

**Comment by x42** [comment]
Actually it seems a *classic* 2nd order biquad also does the trick, and for good measure add a HP to remove any DC offset. Perhaps that's what the website you linked to uses:

![image](https://github.com/user-attachments/assets/c46440d5-49b7-4d92-a9c1-669fd574db1f)


PS. 5kHz for the LPF is a better choice. and also works with the file you provided.

**Comment by cmalvin121** [comment]
Thanks! I will try these methods.
